# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=150)),
                ('calificacion', models.IntegerField()),
            ],
        ),
    ]
