# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 23:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=90)),
                ('titulo_servicios', models.CharField(max_length=250)),
                ('texto_servicios', models.TextField(max_length=2000)),
                ('titulo_mision', models.CharField(max_length=250)),
                ('texto_mision', models.TextField(max_length=2000)),
                ('titulo_vision', models.CharField(max_length=250)),
                ('texto_vision', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='calificacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
