# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170831_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='texto_extra',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='informacion',
            name='titulo_extra',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
