# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170911_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
